---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/controllers
  prune: true
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/values/controller/kind
          value: DaemonSet
        - op: add
          path: /spec/values/controller/service/externalIPs
          value: []
        - op: add
          path: /spec/values/controller/service/nodePorts/http
          value: 30080
        - op: add
          path: /spec/values/controller/service/nodePorts/https
          value: 30443
        - op: add
          path: /spec/values/controller/config/use-proxy-protocol
          value: "true"
        - op: add
          path: /spec/values/controller/config/use-forwarded-headers
          value: "true"
      target:
        kind: HelmRelease
        name: ingress-nginx
        namespace: ingress-nginx

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-staging-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt
